# 每个字符的延迟时间(秒)，控制打字速度
delay_per_char: 0.5

# 是否启用隐藏推理过程
# true: 启用  false: 禁用
hide_reasoning_content: false

# 是否启用分段发送功能
# true: 启用  false: 禁用
enable_split: true

# 超过该字符数的消息将不会分段 (设为0表示不限制)
# 无论是否开启分段功能，都会遵循此设置
max_chars_for_split: 100

# 需要保留的标点符号列表
# 这些标点符号会在显示时保留
keep_punctuation:
- '？'
- '！'
- '?'
- '!'
- '~'
- '〜'

# 需要删除的标点符号列表
# 这些标点符号会在处理时被忽略
skip_punctuation:
- '，'
- '。'
- ','
- '.'
- ':'
- '：'
- '\n'

# 用于分段的标点符号列表
# 遇到这些符号时会将文本分成多段发送
split_punctuation:
- '？'
- '！'
- '?'
- '!'
- '~'
- '〜'
